/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Interfaces;
import TextConverter.*;
import org.jfugue.player.Player;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.net.URL;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

public class InputTela extends javax.swing.JFrame {
    private String nomeMusica= "";
    private String nomeDiretorio = "";

    /**
     * Creates new form inputScreen
     */
    public InputTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        foxslateButton = new javax.swing.JButton();
        voltarMenuButton = new javax.swing.JButton();
        logoInf = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        abrirTxt = new javax.swing.JMenuItem();
        nomeMusicaBotao = new javax.swing.JMenuItem();
        nomeDirMusica = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Foxslator1.0");
        setPreferredSize(new java.awt.Dimension(850, 500));
        setResizable(false);

        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        textArea.setLineWrap(true);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        foxslateButton.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        //foxslateButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\henry\\OneDrive\\Documentos\\NetBeansProjects\\Foxslator\\src\\resources\\raposinha.png")); // NOI18N
        foxslateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raposinha.png")));


        foxslateButton.setText("Foxslate!");
        foxslateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        foxslateButton.setIconTextGap(20);
        foxslateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foxslateButtonActionPerformed(evt);
            }
        });

        voltarMenuButton.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        voltarMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-go-back-48.png")));
        voltarMenuButton.setText("Voltar para o menu");
        voltarMenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    voltarMenuButtonActionPerformed(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        logoInf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoinf2.png"))); // NOI18N

        jMenu2.setText("Arquivos");

        abrirTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-open-file-folder-48.png")));  // NOI18N

        abrirTxt.setText("Abrir arquivo .txt");
        abrirTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirTxtActionPerformed(evt);
            }
        });
        jMenu2.add(abrirTxt);

        nomeMusicaBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-musical-note-48-2.png"))); // NOI18N
        nomeMusicaBotao.setText("Definir Nome do .MIDI");
        nomeMusicaBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeMusicaBotaoActionPerformed(evt);
            }
        });
        jMenu2.add(nomeMusicaBotao);


        nomeDirMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-salvar-48.png")));
        nomeDirMusica.setText("Selecionar Local de Salvamento");
        nomeDirMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDirMusicaActionPerformed(evt);
            }
        });
        jMenu2.add(nomeDirMusica);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(voltarMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(foxslateButton)
                .addGap(29, 29, 29)
                .addComponent(logoInf)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(voltarMenuButton)
                        .addComponent(foxslateButton))
                    .addComponent(logoInf))
                .addGap(71, 71, 71))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abrirTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirTxtActionPerformed

                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setDialogTitle("Selecione o arquivo .TXT a ser lido");
                fileChooser.setFileFilter(new FileNameExtensionFilter("Text files (*.txt)", "txt"));
                int result = fileChooser.showOpenDialog(InputTela.this);
                if (result == JFileChooser.APPROVE_OPTION) {
                    File selectedFile = fileChooser.getSelectedFile();
                    if (selectedFile.getName().endsWith(".txt")) {
                        try {
                            // Read the contents of the file and display it in the text area
                            FileReader reader = new FileReader(selectedFile);
                            BufferedReader br = new BufferedReader(reader);
                            String line;
                            textArea.setText("");
                            while ((line = br.readLine()) != null) {
                                textArea.append(line + "\n");
                            }
                            br.close();
                            reader.close();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(InputTela.this, "Error: " + ex.getMessage());
                        }
                    } else {
                        JOptionPane.showMessageDialog(InputTela.this, "Please select a .txt file.");
                    }
                }
    }//GEN-LAST:event_abrirTxtActionPerformed
                        
    
    private void foxslateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foxslateButtonActionPerformed
    // TODO add your handling code here:
        Player player = new Player();
        Parser parser = new Parser();
        String texto = textArea.getText();
        String musica = parser.convertMelody(texto); 
        String downloadsDirectoryPath = System.getProperty("user.home") + File.separator + "Downloads";
        
        //System.out.println(downloadsDirectoryPath);
        JFugueMusicDownloader downloader = new JFugueMusicDownloader(musica, nomeMusica, nomeDiretorio, downloadsDirectoryPath);
        downloader.downloadMusic();
        System.out.println(texto);
        
        player.play(musica);
    }//GEN-LAST:event_foxslateButtonActionPerformed

    private void voltarMenuButtonActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_voltarMenuButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FoxslatorInit().setVisible(true);
    }//GEN-LAST:event_voltarMenuButtonActionPerformed

    private void nomeMusicaBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeMusicaBotaoActionPerformed
        // TODO add your handling code here:
        nomeMusica = JOptionPane.showInputDialog(null, "Nome da música:");
        if(nomeMusica.isEmpty())
            nomeMusica = "minha_musica";
    }//GEN-LAST:event_nomeMusicaBotaoActionPerformed

    private void nomeDirMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDirMusicaActionPerformed
        // TODO add your handling code here:
        JFrame parentFrame = new JFrame();

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Escolha um diretório:");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int userSelection = fileChooser.showDialog(parentFrame, "Escolher");

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            nomeDiretorio = fileChooser.getSelectedFile().getPath();
        }
    }//GEN-LAST:event_nomeDirMusicaActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirTxt;
    private javax.swing.JButton foxslateButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoInf;
    private javax.swing.JMenuItem nomeDirMusica;
    private javax.swing.JMenuItem nomeMusicaBotao;
    private javax.swing.JTextArea textArea;
    private javax.swing.JButton voltarMenuButton;
    // End of variables declaration//GEN-END:variables
}
